### PR TITLE
Added tests for the examples

### LINKED ISSUE #3: Examples need their tests moved into this repo
Title says it all

### PR DESCRIPTION
**Pull request by cogmission**
Fixes #3

### CODE REVIEW

**Comment by cogmission** [comment]
@rhyolight All Yours!

**Comment by rhyolight** [comment]
Is there a PR to remove this code from htm.java?

**Comment by cogmission** [comment]
Not yet. I'm multitasking (maybe not too well?) :-P

**Comment by cogmission** [comment]
Done. See https://github.com/numenta/htm.java/issues/283

**Pull request merged**
